### PR TITLE
Accessibility check branch

### PR DESCRIPTION
**Pull request by Besufekad-HAZ**
-Add h1 heading
-Add a main landmark
-Fix the list html structure

### CODE REVIEW

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi @Besufekad-HAZ  @Ellon-M    , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional  README 
✔️ Good commit messages

almost

## Required Changes ♻️

- [ ] As Stated in the project Kindly Prepare a report listing all points that you have checked, and the result of your evaluation and Add your report to the description of your pull request..  Your report should include:

Capture

- [ ] Kindly give Better page titles: like "Besufekad portfolio"or "Besufekad full-stack web-developer". It adequately and briefly describes the content of the page.
- [ ] 
https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/blob/b16e58cd117778376deba106751f1f64dc6fce42/index.html#L18

_Check  the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
### **Page titles:**

The page title had been changed from the default title ‘My personal Portfolio’ to  Besufekad's Portfolio’

https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/pull/12/commits/2406a09e31f7523e178515b42141d8b4acfd1a5f

### Image text alternatives :

No changes are required in this section.

### Text headings :

added only one h1 heading while the previous section doesn't contain an h1.

https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/pull/12/commits/b16e58cd117778376deba106751f1f64dc6fce42

### Color contrast

No changes are required in this section.

### Resize

No changes are required in this section.

### Interaction 

No changes are required in this section.

### Moving content

No changes are required in this section.

### Multimedia

No changes are required in this section.

### The basic structure of the page

Added a main landmark, fixed the list HTML structure

https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/pull/12/commits/b16e58cd117778376deba106751f1f64dc6fce42

**Comment by Besufekad-HAZ** [comment]
> ### **Page titles:**
> The page title had been changed from the default title ‘My personal Portfolio’ to Besufekad's Portfolio’
> 
> [2406a09](https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/commit/2406a09e31f7523e178515b42141d8b4acfd1a5f)
> 
> ### Image text alternatives :
> No changes are required in this section.
> 
> ### Text headings :
> added only one h1 heading while the previous section doesn't contain an h1.
> 
> [b16e58c](https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/commit/b16e58cd117778376deba106751f1f64dc6fce42)
> 
> ### Color contrast
> No changes are required in this section.
> 
> ### Resize
> No changes are required in this section.
> 
> ### Interaction
> No changes are required in this section.
> 
> ### Moving content
> No changes are required in this section.
> 
> ### Multimedia
> No changes are required in this section.
> 
> ### The basic structure of the page
> Added a main landmark, fixed the list HTML structure
> 
> [b16e58c](https://github.com/Besufekad-HAZ/Portfolio-Setup-Mob-/commit/b16e58cd117778376deba106751f1f64dc6fce42)

**Review by mckent05 — APPROVED** [review]
Hi guys,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
approved


## Highlights
- Good job making the requested changes 👍 👍 
- Your report looks good 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
